---
- stat: path=/opt/kibana/bin/kibana
  register: kibana_install

- name: Download and install the RPM
  yum: name=https://download.elastic.co/kibana/kibana/kibana-4.6.1-x86_64.rpm state=present
  notify: restart kibana
  when:
    - kibana_install.stat.exists == False

- name: Start Kibana
  service: name=kibana state=restarted enabled=yes

- name: Set to autostart
  shell: chkconfig --add kibana

- name: Install Deps
  yum: name={{ item }} state=present
  with_items:
  - libstdc++
  - glibc

- name: Allow incoming connections
  iptables: chain=INPUT
            action=insert
            source=0.0.0.0/0
            protocol=tcp
            match=tcp
            state=present
            ctstate=NEW
            destination_port=5601
            jump=ACCEPT
